name: Scrape

on:
  schedule:
    # Every 20 minutes
    - cron:  '0,20,40 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run scrape
      - run: |
          git config user.name github-actions-bot
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Scrape completed"
          git push
